# Generated by Django 2.0.13 on 2019-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='yourname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
