# Generated by Django 2.0.13 on 2019-04-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0002_auto_20190401_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('fees', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
