# Generated by Django 2.0.13 on 2019-04-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0005_ngo_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='map',
            field=models.CharField(max_length=1000),
        ),
    ]
