# Generated by Django 2.0.13 on 2019-04-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0007_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
    ]
