# Generated by Django 2.0.13 on 2019-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0008_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaid',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
