# Generated by Django 2.0.13 on 2019-04-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0009_firstaid_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vet',
            new_name='VetRegister',
        ),
        migrations.RenameModel(
            old_name='Volunteer',
            new_name='VolunteerRegister',
        ),
    ]
