# Generated by Django 2.0.13 on 2019-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet2Vet', '0010_auto_20190407_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateform',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
